apiVersion: v1
kind: Pod
metadata:
  name: hello-kubernetes
  labels:
    name: hello-kubernetes
spec:
  containers:
  - name: hello-kubernetes
    image: hambalee/hello-kubernetes:1.0.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
